# Generated by Django 3.2.14 on 2022-07-14 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertime',
            name='book',
        ),
        migrations.RemoveField(
            model_name='ordertime',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderTime',
        ),
    ]
